baseURL: /
title: Neil Fasching
theme: hugo-eureka
paginate: 3
copyright: '&copy; 2021'
enableEmoji: yes
enableGitInfo: no
summaryLength: 75
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
    noClasses: no
  tableOfContents:
    endLevel: 6
    ordered: no
    startLevel: 2
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
build:
  useResourceCacheWhen: always
